cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      logged_in: false
      name: John Smith
      password: abc
preauthorized:
  emails:
  - melsby@gmail.com
